# Generated by Django 3.0.6 on 2020-09-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='category',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
