# Generated by Django 3.0.6 on 2020-09-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_datamodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='datafile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='category',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
