# Generated by Django 3.0.6 on 2020-09-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_auto_20200921_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('registration', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('event_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='datafile',
            field=models.FileField(upload_to=''),
        ),
    ]
