# Generated by Django 3.0.6 on 2020-09-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0004_auto_20200923_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneevents',
            name='upcoming',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doneevents',
            name='registration',
            field=models.URLField(null=True),
        ),
    ]
