# Generated by Django 3.0.6 on 2020-09-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0007_showcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showcase',
            old_name='imag3',
            new_name='image3',
        ),
    ]
