# Generated by Django 3.0.6 on 2020-09-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0008_auto_20200923_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Showcase',
        ),
    ]
